name: Flutter CI

# This workflow is triggered on pushes to the repository.

on:
  push:
    branches:
      - master

# on: push    # Default will running for every branch.

jobs:
  test:
    name: Run tests
    # This job will run on ubuntu virtual machine
    runs-on: ubuntu-latest
    steps:
      # Setup the flutter environment.
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable' # or: 'beta' or 'master'

      # Get pub packages
      - run: flutter packages get

      # Build generated classes
      # - run: flutter pub run build_runner build

      - run: flutter test

