name: Flutter CI

# This workflow is triggered on pushes to the repository.

on:
  push:
    branches:
      - main

# on: push    # Default will running for every branch.

jobs:
  test:
    name: Run tests
    # This job will run on ubuntu virtual machine
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Setup the flutter environment.
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable' # or: 'beta' or 'master'

      # Get pub packages
      - run: flutter pub get

      # Build generated classes
      - run: flutter pub run build_runner build

      # Analyze project
      - run: flutter analyze

      # Run tests
      - run: flutter test --coverage

      # Upload codecoverage to app.codecov.io
      - uses: codecov/codecov-action@v1.0.2
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ./coverage/lcov.info


